name: Run Shell Script

on:
  push:
    branches:
      - main  # Vous pouvez changer "main" pour une autre branche

jobs:
  run-script:
    runs-on: ubuntu-latest  # Utilise une image Ubuntu pour exécuter le script

    steps:
      # Étape 1 : Vérifier le dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Exécuter le script shell
      - name: Run shell script
        run: ./c-wire.sh  
