name: git-bash

on:
  push:
    branches:
      - main
      
permissions:
  contents: write  # Cela accorde les droits de modification sur le contenu du dépôt


jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Git Bash
        uses: pkg-src/github-action-git-bash@v1.1

      - name: Change permissions for script
        run: chmod 700 c-wire.sh

      - name: Run bash script
        run: ./c-wire.sh c-wire_v00.dat hvb comp
